version: '3.9'

x-redmine: &redmine
  image: redmine
  build: .
  env_file:
    - docker.env
  ports:
    - 8080:8080
    - 3333:2222 # 2222 is used by Codespaces
  volumes:
    - ./data/wwwroot:/home/site/wwwroot

services:
  redmine-sqlite:
    <<: *redmine
    environment:
      DATABASE_URL: sqlite3:/home/site/wwwroot/redmine.sqlite3
    profiles: [sqlite]

  redmine-mysql:
    <<: *redmine
    environment:
      DATABASE_URL: mysql2://redmineuser:redminesecret@mysql/redminedb?encoding=utf8mb4
      DB_ADMIN_CMD: mysql -vv -u root -h mysql
    depends_on: [mysql]
    profiles: [mysql]

  redmine-mariadb:
    <<: *redmine
    environment:
      DATABASE_URL: mysql2://redmineuser:redminesecret@mariadb/redminedb?encoding=utf8mb4
      DB_ADMIN_CMD: mysql -vv -u root -h mariadb
    depends_on: [mariadb]
    profiles: [mariadb]

  redmine-postgres:
    <<: *redmine
    environment:
      DATABASE_URL: postgresql://redmineuser:redminesecret@postgres/redminedb
      DB_ADMIN_CMD: psql -e postgresql://postgres:adminsecret@postgres
    depends_on: [postgres]
    profiles: [postgres]

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./data/mysql:/var/lib/mysql
    profiles: [mysql]

  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    volumes:
      - ./data/mariadb:/var/lib/mysql
    profiles: [mariadb]

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: adminsecret
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    profiles: [postgres]
