on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
permissions:
  contents: read
  packages: write
env:
  REGISTRY: ghcr.io
  IMAGE: "${{github.repository}}/redmine"
  REDMINE_REPOSITORY: redmine/redmine
  REDMINE_REF: "5.1.0"
  EASYAUTH_REPOSITORY: yaegashi/redmine_easyauth
  EASYAUTH_REF: master
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Checkout redmine
        uses: actions/checkout@v3
        with:
          repository: "${{env.REDMINE_REPOSITORY}}"
          ref: "${{env.REDMINE_REF}}"
          path: redmine
      -
        name: Checkout redmine_easyauth plugin
        uses: actions/checkout@v3
        with:
          repository: "${{env.EASYAUTH_REPOSITORY}}"
          ref: "${{env.EASYAUTH_REF}}"
          path: redmine/plugins/redmine_easyauth
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: "${{env.REGISTRY}}/${{env.IMAGE}}"
          tags: |
            type=ref,event=branch,prefix=${{env.REDMINE_REF}}-
            type=ref,event=tag,prefix=${{env.REDMINE_REF}}-
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ startsWith(github.ref, 'refs/tags/') && format('{0}/{1}:{2}', env.REGISTRY, env.IMAGE, env.REDMINE_REF) || '' }}
          labels: |
            ${{ steps.meta.outputs.labels }}